# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Watchlist.delete_all
Viewer.delete_all
Movie.delete_all

movie_one = Movie.create(title: "Once Upon A Time in Hollywood", release: "2019", director: "Quentin Tarantino", image_url: "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Drama", description:"A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.")
movie_two= Movie.create(title: "Uncut Gems", release: "2019", director:"Benny Safdie, Josh Safdie", image_url: "https://m.media-amazon.com/images/M/MV5BZDhkMjUyYjItYWVkYi00YTM5LWE4MGEtY2FlMjA3OThlYmZhXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Drama", description:"With his debts mounting and angry collectors closing in, a fast-talking New York City jeweler risks everything in hope of staying afloat and alive.")
movie_three= Movie.create(title: "The Gentlemen", release: "2019", director: "Guy Ritchie" ,image_url: "https://m.media-amazon.com/images/M/MV5BMTlkMmVmYjktYTc2NC00ZGZjLWEyOWUtMjc2MDMwMjQwOTA5XkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Action", description:"An American expat tries to sell off his highly profitable marijuana empire in London, triggering plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.")
movie_four = Movie.create(title: "1917", release: "2019", director: "Sam Mendes" ,image_url: "https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Drama", description: "April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.")
movie_five = Movie.create(title: "The Call Of The Wild", release: "2019", director: "Chris Sanders" ,image_url: "https://m.media-amazon.com/images/M/MV5BNWI1YzQwMDQtNzczMC00YWQ2LThmNjMtMThkMTFhNjBmMmQ3XkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Adventure" ,description: "A sled dog struggles for survival in the wilds of the Yukon.")
movie_six = Movie.create(title: "Birds of Prey...",release: "2020", director: "Cathy Yan" ,image_url: "https://m.media-amazon.com/images/M/MV5BMzQ3NTQxMjItODBjYi00YzUzLWE1NzQtZTBlY2Y2NjZlNzkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", genre:"Action" ,description: "After splitting with the Joker, Harley Quinn joins superheroes Black Canary, Huntress and Renee Montoya to save a young girl from an evil crime lord.")
movie_seven = Movie.create(title: "Jojo Rabbit", release: "2019", director: "Taika Waititi" ,image_url: "https://m.media-amazon.com/images/M/MV5BZjU0Yzk2MzEtMjAzYy00MzY0LTg2YmItM2RkNzdkY2ZhN2JkXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Drama", description: "A young boy in Hitler's army finds out his mother is hiding a Jewish girl in their home.")
movie_eight = Movie.create(title: "The Last Thing He Wanted",release: "2020", director: "Dee Rees" ,image_url: "https://m.media-amazon.com/images/M/MV5BMWI3ODZlNjgtNWM4OC00MDFhLTg2MmYtYjk3M2I0OWJmZmE2XkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Action", description: "A veteran D.C. journalist loses the thread of her own narrative when a guilt-propelled errand for her father thrusts her from byline to unwitting subject in the very story she's trying to break. Adapted from Joan Didion's namesake novel.")
movie_nine = Movie.create(title: "Candyman", release: "2020", director:"Nia DaCosta" ,image_url:"https://m.media-amazon.com/images/M/MV5BM2RiMzdmZjYtY2VhZS00YzQ4LWIzNjItYWY5ZTFiNTI0ZGU3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Horror", description: "A spiritual sequel to the 1992 horror film 'Candyman' that returns to the now-gentrified Chicago neighborhood where the legend began.")
movie_ten = Movie.create(title: "Sonic the Hedgehog", release: "2020", director: "Jeff Fowler" ,image_url: "https://m.media-amazon.com/images/M/MV5BNDc1ZTlmOWUtNDY2YS00OGU5LTg2MTYtYTk2MmQzMGE2NzUwXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_UX182_CR0,0,182,268_AL_.jpg", genre:"Adventure", description: "After discovering a small, blue, fast hedgehog, a small-town police officer must help it defeat an evil genius who wants to do experiments on it.")
movie_eleven = Movie.create(title: "Knives out", release: "2019", director: "Rian Johnson", image_url: "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_.jpg", genre: "Suspense", description: "A detective investigates the death of a patriarch of an eccentric, combative family.")
movie_tweleve = Movie.create(title: "The Invisible Man ", release: "2020", director: "Leigh Whannell", image_url: "https://upload.wikimedia.org/wikipedia/en/3/3a/The_Invisible_Man_%282020_film%29_-_release_poster.jpg", genre: "Horror", description: "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.")
movie_thirteen = Movie.create(title: "Parasite", release: "2019", director: "Bong Joon Ho", image_url: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UY1200_CR90,0,630,1200_AL_.jpg", genre: "Horror", description: "A poor family, the Kims, con their way into becoming the servants of a rich family, the Parks. But their easy life gets complicated when their deception is threatened with exposure.")
movie_fourteen = Movie.create(title: "Midsommar", release: "2019", director: "Ari Aster", image_url: "https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Horror" , description: "A couple travels to Sweden to visit a rural hometown's fabled mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.")
movie_fifteen = Movie.create(title: "Bombshell", release: "2019", director: "Jay Roach", image_url: "https://m.media-amazon.com/images/M/MV5BZjlhOWE3YjktY2MzOC00ZmQ1LWIwNjgtZmVhZmFjZGExMzgyXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Drama" ,description: "A group of women take on Fox News head Roger Ailes and the toxic atmosphere he presided over at the network.")
movie_sixteen = Movie.create(title: "A Quiet Place Part II", release: "2020", director: "John Krasinski" ,image_url: "https://m.media-amazon.com/images/M/MV5BN2NiMjEyZjAtNzYyYi00YjI3LThhZTYtMzkyZTkxYzgwMzI2XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Horror" ,description: "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize the creatures that hunt by sound are not the only threats lurking beyond the sand path. ")
movie_seventeen = Movie.create(title: "Run", release: "2020", director: "Aneesh Chaganty", image_url: "https://m.media-amazon.com/images/M/MV5BYzQ2MDdiMDEtNmYyMC00N2NmLWFiZjAtZDYwMzMzY2VhZDM1XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SY1000_SX675_AL_.jpg", genre:"Horror" ,description: "A homeschooled teenager begins to suspect her mother is keeping a dark secret from her.")
movie_eighteen = Movie.create(title: "Emma", release: "2019", director: "Autumn de Wilde", image_url: "https://m.media-amazon.com/images/M/MV5BOGRiODEzM2QtOTUyYi00MWRlLTg4MzMtZGI0YmUzNWUyMjQ0XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX182_CR0,0,182,268_AL_.jpg", genre:"Comedy" ,description: "In 1800s England, a well meaning but selfish young woman meddles in the love lives of her friends.")
movie_nineteen = Movie.create(title: "Joker", release: "2019", director: "Todd Phillips", image_url: "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", genre:"Drama" ,description: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.")
movie_20 = Movie.create(title: "Frozen II", release: "2019", director: "Chris Buck, Jennifer Lee", image_url: "https://m.media-amazon.com/images/M/MV5BMjA0YjYyZGMtN2U0Ni00YmY4LWJkZTItYTMyMjY3NGYyMTJkXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Adventure", description:"Anna, Elsa, Kristoff, Olaf and Sven leave Arendelle to travel to an ancient, autumn-bound forest of an enchanted land. They set out to find the origin of Elsa's powers in order to save their kingdom.")

movie_21 = Movie.create(title: "Charlie's Angels", release: "2019", director: "Elizabeth Banks", image_url: "https://m.media-amazon.com/images/M/MV5BN2VkMjQwZWMtMzc1NC00ZjJiLWJlNTMtNmRjOTE2ZTJmYzUwXkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_UY268_CR7,0,182,268_AL_.jpg", genre: "Action", description:"When a young systems engineer blows the whistle on a dangerous technology, Charlie's Angels are called into action, putting their lives on the line to protect us all.")


movie_22 = Movie.create(title: "Bad Boys for Life", release: "2020", director: "Adil El Arbi, Bilall Fallah", image_url: "https://m.media-amazon.com/images/M/MV5BMWU0MGYwZWQtMzcwYS00NWVhLTlkZTAtYWVjOTYwZTBhZTBiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Comedy", description:"The Bad Boys Mike Lowrey and Marcus Burnett are back together for one last ride in the highly anticipated Bad Boys for Life.")

movie_23 = Movie.create(title: "Terminator: Dark Fate", release: "2019", director: "Tim Miller", image_url: "https://m.media-amazon.com/images/M/MV5BOWExYzVlZDgtY2E1ZS00NTFjLWFmZWItZjI2NWY5ZWJiNTE4XkEyXkFqcGdeQXVyMTA3MTA4Mzgw._V1_UX182_CR0,0,182,268_AL_.jpg", genre: "Action", description:"An augmented human and Sarah Connor must stop an advanced liquid Terminator, from hunting down a young girl, whose fate is critical to the human race.")

movie_24 = Movie.create(title: "Rocketman", release: "2019", director: "Dexter Fletcher", image_url: "https://m.media-amazon.com/images/M/MV5BYmIzNjUxZGQtYjg0OS00MmE0LTgwZDAtMzVmODQ2MGI5MTQ5XkEyXkFqcGdeQXVyMTA3MTA4Mzgw._V1_SY1000_CR0,0,666,1000_AL_.jpg", genre: "Drama", description:"A musical fantasy about the fantastical human story of Elton John's breakthrough years.")


movie_25 = Movie.create(title: "Alita: Battle Angel", release: "2019", director: "Robert Rodriguez", image_url: "https://m.media-amazon.com/images/M/MV5BNzVhMjcxYjYtOTVhOS00MzQ1LWFiNTAtZmY2ZmJjNjIxMjllXkEyXkFqcGdeQXVyNTc5OTMwOTQ@._V1_.jpg", genre: "Sci-fi", description:"A deactivated cyborg is revived, but cannot remember anything of her past life and goes on a quest to find out who she is.")


movie_26 = Movie.create(title: "Pan's Labyrinth ", release: "2006", director: "Guillermo del Toro", image_url: "https://m.media-amazon.com/images/M/MV5BMTU3ODg2NjQ5NF5BMl5BanBnXkFtZTcwMDEwODgzMQ@@._V1_SY1000_CR0,0,679,1000_AL_.jpg", genre: "Fantasy", description:"In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.")



movie_27 = Movie.create(title: "Hail, Caesar!", release: "2016", director: "Ethan Coen, Joel Coen", image_url: "https://m.media-amazon.com/images/M/MV5BOTI1M2FlMzItY2VjYS00Y2VkLWI5OTQtMzA0MWMyNmQzZmQ0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg", genre: "Comedy", description:"A Hollywood fixer in the 1950s works to keep the studio's stars in line.")

movie_28 = Movie.create(title: "Jumanji: The Next Level ", release: "2019", director: "Jake Kasdan", image_url: "https://m.media-amazon.com/images/M/MV5BOTVjMmFiMDUtOWQ4My00YzhmLWE3MzEtODM1NDFjMWEwZTRkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg", genre:"Adventure" ,description: "In Jumanji: The Next Level, the gang is back but the game has changed. As they return to rescue one of their own, the players will have to brave parts unknown from arid deserts to snowy mountains, to escape the world's most dangerous game.")

movie_29 = Movie.create(title: "The Lord of the Rings: The Fellowship of the Ring", release: "2001", director: "Peter Jackson", image_url: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SY999_CR0,0,673,999_AL_.jpg", genre:"Fantasy",description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.")
movie_30 = Movie.create(title: "Harry Potter and the Deathly Hallows: Part 2", release: "2011", director: "David Yates", image_url: "https://m.media-amazon.com/images/M/MV5BMjIyZGU4YzUtNDkzYi00ZDRhLTljYzctYTMxMDQ4M2E0Y2YxXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX667_CR0,0,667,999_AL_.jpg", genre:"Fantasy",description: "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.")
movie_31 = Movie.create(title: "The Hitchhiker's Guide to the Galaxy", release: "2005", director: "Garth Jennings", image_url: "https://m.media-amazon.com/images/M/MV5BZmU5MGU4MjctNjA2OC00N2FhLWFhNWQtMzQyMGI2ZmQ0Y2YyL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SY1000_CR0,0,677,1000_AL_.jpg", genre:"Sci-fi",description: "Mere seconds before the Earth is to be demolished by an alien construction crew, journeyman Arthur Dent is swept off the planet by his friend Ford Prefect, a researcher penning a new edition of The Hitchhiker's Guide to the Galaxy.")


10.times do
    Viewer.create(username: Faker::Name.first_name)
end

